# Dockerfile.dev

FROM node:22-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    curl \
    git \
    vim \
    nano \
    inotify-tools \
    && rm -rf /var/lib/apt/lists/*

COPY package*.json ./

RUN npm install



EXPOSE 8000

CMD ["npm", "run", "start:dev"]
