name: CI - BUILD AND RELEASE BACKEND

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      NODE_ENV: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.15.2
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Format
        run: npm run format

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v7
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch

      - name: Archive Build Artifacts
        run: |
          tar -czf build-${{steps.tag_version.outputs.new_tag}}.tar.gz dist

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Releasse ${{steps.tag_version.outputs.new_tag}}
          path: build-${{steps.tag_version.outputs.new_tag}}.tar.gz

      - name: Upload to GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{steps.tag_version.outputs.new_tag}}
          name: ${{steps.tag_version.outputs.new_tag}}
          files: |
            build-${{steps.tag_version.outputs.new_tag}}.tar.gz

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: ✅ DONE!
        run: echo "PIPLINE SUCCESSFULLY COMPLETED ✅✅"

permissions:
  contents: write
  packages: write
